library(jsonlite)

# Exports the stuff the web app needs to pick locations the same way 02_locations.R does:
# the borough polygons straight out of 01_borders.R, plus the metro/subway station lists.
# Run this whenever the polygons change. The app reads the json, R stays the source of truth.
#
# Output: react_frontend/src/data/regions.json

repo <- getwd()
out_file <- file.path(repo, "react_frontend", "src", "data", "regions.json")
dir.create(dirname(out_file), recursive = TRUE, showWarnings = FALSE)

# 01_borders.R wants the percents defined, but they only set the cumulative cutoffs,
# they don't touch the coordinates. Powers of two so the NYC sum check lands exactly on 1.
as_ring <- function(m) unname(lapply(seq_len(nrow(m)), function(i) c(m[i, 1], m[i, 2])))

city <- "DC"
at_large_percent <- .5; downtown_percent <- .15
greater_central_percent <- .25; metro_percent <- .1
source(file.path(repo, "01_borders.R"))
dc_polys <- list(
  at_large        = as_ring(at_large_coords),
  downtown        = as_ring(downtown_coords),
  greater_central = as_ring(greater_central_coords)
)

city <- "NYC"
manhattan_percent <- .5; brooklyn_percent <- .25
queens_percent <- .125; bronx_percent <- .125
subway_percent <- 0   # skip the gtfs download in 01_borders.R, we pull stops below
source(file.path(repo, "01_borders.R"))
nyc_polys <- list(
  manhattan = as_ring(manhattan_coords),
  brooklyn  = as_ring(brooklyn_coords),
  queens    = as_ring(queens_coords),
  bronx     = as_ring(bronx_coords)
)

# --- NYC subway stations, straight from the MTA feed (same filter as 02_locations.R) ---
nyc_stations <- list()
try({
  zip_path <- tempfile(fileext = ".zip")
  download.file("http://web.mta.info/developers/data/nyct/subway/google_transit.zip",
                zip_path, quiet = TRUE)
  stops <- read.csv(unz(zip_path, "stops.txt"), stringsAsFactors = FALSE)
  stops <- stops[stops$location_type == 1 & stops$stop_lon > -74.051977, ]
  stops <- unique(stops[, c("stop_name", "stop_lat", "stop_lon")])
  nyc_stations <- unname(lapply(seq_len(nrow(stops)), function(i) {
    list(name = stops$stop_name[i], lat = stops$stop_lat[i], lng = stops$stop_lon[i])
  }))
  message("NYC: ", length(nyc_stations), " subway stations")
}, silent = TRUE)

# --- DC metro stations. Uses the metro package when it's around (Jay's setup),
# otherwise falls back to OpenStreetMap so this works without a WMATA key. ---
dc_stations <- list()
drop_stations <- c("Friendship Heights", "Deanwood", "Takoma")
if (requireNamespace("metro", quietly = TRUE) && Sys.getenv("WMATA_API_KEY") != "") {
  try({
    st <- metro::rail_stations(LineCode = NULL,
                               api_key = metro::wmata_key(Sys.getenv("WMATA_API_KEY")))
    st <- st[st$State == "DC" & !(st$StationName %in% drop_stations), ]
    st <- unique(data.frame(name = st$StationName, lat = st$Lat, lng = st$Lon))
    dc_stations <- unname(lapply(seq_len(nrow(st)), function(i) as.list(st[i, ])))
    message("DC: ", length(dc_stations), " metro stations (WMATA)")
  }, silent = TRUE)
}
if (length(dc_stations) == 0) {
  # DC open data, no key needed, so this works on anyone's machine
  try({
    url <- paste0("https://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/",
                  "Transportation_Rail_Bus_WebMercator/MapServer/52/query",
                  "?where=1%3D1&outFields=NAME&outSR=4326&f=json")
    res <- fromJSON(url)
    st <- data.frame(name = res$features$attributes$NAME,
                     lat  = res$features$geometry$y,
                     lng  = res$features$geometry$x,
                     stringsAsFactors = FALSE)
    st <- unique(st[!(st$name %in% drop_stations), ])
    dc_stations <- unname(lapply(seq_len(nrow(st)), function(i) as.list(st[i, ])))
    message("DC: ", length(dc_stations), " metro stations (DC open data)")
  }, silent = TRUE)
}
if (length(dc_stations) == 0) {
  warning("No DC metro stations exported, the app will spread that weight across the other areas")
}

regions <- list(
  note = "Generated by 08_export_regions.R, don't hand edit. Polygons come from 01_borders.R.",
  generated = format(Sys.time(), "%Y-%m-%d"),
  minSpacingMeters = 314,   # same spacing rule as 02_locations.R
  DC  = list(polygons = dc_polys,  stations = dc_stations,  stationKey = "metro"),
  NYC = list(polygons = nyc_polys, stations = nyc_stations, stationKey = "subway")
)

write(toJSON(regions, auto_unbox = TRUE, digits = 8, pretty = TRUE), out_file)
message("Wrote ", out_file)
